### PR TITLE
Badges with versions

### PR DESCRIPTION
**Pull request by abelsiqueira**
Something like this:

image

I still need to figure out how to "counter" `@showall = true`.
- If enabled, the black box appears
- If disabled, I will have to manually add each output of the literate file - which is undesirable.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
This is the result:

image

image

image

**Review by tmigot — APPROVED** [review]
Awesome! Thanks

**Review by dpo — APPROVED** [review]
Excellent! Thank you!

**Comment by abelsiqueira** [comment]
Thanks for the reviews :+1:

**Pull request merged**
