### PR TITLE
Updates from JSOTutorials

### PR DESCRIPTION
**Pull request by abelsiqueira**
Updates from jsotutorials-push-5a9ce0271cda93d0968910e7c83658dea174cb64

### CODE REVIEW

**Comment by tmigot** [comment]
#51

**Comment by tmigot** [comment]
@abelsiqueira Not sure, why it failed. Is it because the doc ends with a block of code?

**Comment by abelsiqueira** [comment]
The `@example` are not valid Franklin. Are they valid Weave?

**Comment by tmigot** [comment]
Argh, ok, thanks! I missed that the result of each cell didn't actually show.

**Pull request closed without merging**
