### PR TITLE
Update articles2023.bib

### PR DESCRIPTION
**Pull request by tmigot**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
@frapac, can you review?

**Comment by tmigot** [comment]
Hi added the bug label, because it seems that the incollection doesn't show here https://jso-preview.netlify.app/previews/pr179/references/

**Comment by abelsiqueira** [comment]
Should be fixed now:
image

**Comment by tmigot** [comment]
Thanks !

**Review by frapac — APPROVED** [review]
This looks good to me. Good to know we have this database, I will make a PR once we release the MadNLP paper.

**Pull request merged**
