### PR TITLE
New tutorial: Introduction to BenchmarkProfiles

### PR DESCRIPTION
**Pull request by abelsiqueira**
https://jso-docs.github.io/introduction-to-benchmarkprofiles/

### CODE REVIEW

**Comment by dpo** [comment]
Not sure where the contents of the tutorial is, but on the final plot, the y label doesn't correspond to the command.

**Comment by abelsiqueira** [comment]
That's interesting, I had not noticed that before. But indeed, that is what is currently being run and created.

- The current tutorial: https://juliasmoothoptimizers.github.io/BenchmarkProfiles.jl/stable/tutorial/
- The code for the jso-docs: https://github.com/jso-docs/introduction-to-benchmarkprofiles/blob/main/index.jl

**Comment by abelsiqueira** [comment]
It's fixed in the latest version.

**Comment by dpo** [comment]
Thanks!

**Pull request merged**
