### PR TITLE
Updates from JSOTutorials

### PR DESCRIPTION
**Pull request by abelsiqueira**
Updates from jsotutorials-push-2ddd68b1184cf54535fea2cf0f815ec7a3297008

### CODE REVIEW

**Comment by tmigot** [comment]
Looks great! https://jso-preview.netlify.app/previews/pr76/tutorials/introduction-to-adnlpmodels/
It definitely shows that we need a better print of ADNLPModel^^.

**Comment by abelsiqueira** [comment]
Very nice. Thanks a lot. I'm merging this and closing the other PRs.

**Comment by abelsiqueira** [comment]
By the way, we still need a PR to the `_data/tutorials.json` file for this go to live.

**Comment by tmigot** [comment]
https://github.com/JuliaSmoothOptimizers/JuliaSmoothOptimizers.github.io/pull/77

**Pull request merged**
